import { env } from "../configs/env";

export const ACCESS_TOKEN_SECRET = env.ACCESS_JWT_SECRET;
export const ACCESS_TOKEN_EXPIRED_IN_SEC = env.ACCESS_JWT_EXPIRED_SEC; // seconds
export const ACCESS_TOKEN_EXPIRED_IN_MILL_SEC =
  ACCESS_TOKEN_EXPIRED_IN_SEC * 1000;

export const REFRESH_TOKEN_SECRET = env.REFRESH_JWT_SECRET;
export const REFRESH_TOKEN_EXPIRED_IN_SEC = env.REFRESH_JWT_EXPIRED_SEC; // seconds
export const REFRESH_TOKEN_EXPIRED_IN_MILL_SEC =
  REFRESH_TOKEN_EXPIRED_IN_SEC * 1000;

export const SIGN_UP_TOKEN_SECRET = env.SIGN_UP_JWT_SECRET;
export const SIGN_UP_TOKEN_EXPIRED_IN_SEC = env.SIGN_UP_JWT_EXPIRED_SEC; // seconds
export const SIGN_UP_TOKEN_EXPIRED_IN_MILL_SEC =
  SIGN_UP_TOKEN_EXPIRED_IN_SEC * 1000;
