import * as v1 from "./v1";

export const SUBSCRIPTION_ROUTES = {
  v1: v1.SUBSCRIPTION_ROUTES,
};

export const SUBSCRIPTION_LEDGER_ROUTES = {
  v1: v1.SUBSCRIPTION_LEDGER_ROUTES,
};

export const PLATFORM_SUBSCRIPTION_ROUTES = {
  v1: v1.PLATFORM_SUBSCRIPTION_ROUTES,
};

export const REVENUE_ROUTES = {
  v1: v1.REVENUE_ROUTES,
};
